### PR TITLE
212 admin add panel for student information

### PR DESCRIPTION
**Pull request by DallinFromEarth**
There is now a new tab: "students"

This tab shows a list of all students from the server database, their netID, and a clickable Github URL. Clicking on either the student's name or netID will open up a pop-up window with all of their submissions. (Which you can then open another pop-up in)

### CODE REVIEW

**Comment by DallinFromEarth** [comment]
branch #158 has taken the new table library used for the student tab in this pr, and applied it to the submissions tab. Theres still a few small front-end things to update there, but that can be pulled into this pr if it makes more sense.

**Review by 19mdavenport — COMMENTED** [review]
I don't want to approve this for merging without @pawlh seeing this but this looks pretty good to me 👍

**Review by 19mdavenport — DISMISSED** [review]
Is there a yarn dependency that needs to be added for ag-grid-vue3?

**Review by pawlh — APPROVED** [review]
❤️

**Pull request merged**
